config/routes.rb
Rails.application.routes.draw do
  resources :routines
  resources :products
  
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => 'callbacks'}
  root to: 'application#welcome'

    resources :products do
      resources :routines
    end

  devise_scope :user do
    get 'login', to:'devise/sessions#new', as: 'login'
    get 'signup', to:'devise/registrations#new', as: 'signup'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  scope :popular, -> {group('name').order('count_all').limit(1).count}
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    scope :strong, -> {where.not(active_ingredient_2: "")}
    has_many :routines
    has_many :users, :through => :routines

    validates :name, presence: true
    validates :name, uniqueness: true
    validates :active_ingredient_1, presence: true

end

app/models/routine.rb
class Routine < ApplicationRecord
    belongs_to :user
    belongs_to :product

    validates :name, presence: true
    validates :name, uniqueness: true

    accepts_nested_attributes_for :product, reject_if: :all_blank
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :routines
  has_many :products, :through => :routines

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user| 
      user.provider = auth.provider 
      user.username = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0..20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def welcome
        @routines = Routine.all
        @products = Product.all
        @popular_product = Product.all.popular
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])

        sign_in_and_redirect @user
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :user_signed_in?

  def index
    @products = current_user.products.uniq
    @strong_products = current_user.products.strong.uniq
  end

  def show
    @product = current_user.products.find_by(id: params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:name, :active_ingredient_1, :active_ingredient_2)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :user_signed_in?

  def index
    if params[:product_id]
      @routines = current_user.routines.where(product_id: params[:product_id])
      @product = current_user.products.find_by(id: params[:product_id])
    else
      @routines = current_user.routines
    end
  end

  def show
    @routine = current_user.routines.find_by(id: params[:id])
  end

  def new
    @routine = current_user.routines.build
    @product = @routine.build_product
  end

  def edit
    @routine = current_user.routines.find_by(id: params[:id])
  end

  def create
    @routine = current_user.routines.build(routine_params)
    if @routine.save 
      redirect_to routine_path(@routine)
    else
      render :new
    end
  end

  def update
    @routine = current_user.routines.find_by(id: params[:id])
    @routine.update(routine_params)

    redirect_to routine_path(@routine)
  end

  def destroy
    @routine = current_user.routines.find_by(id: params[:id])
    @routine.destroy

    redirect_to routines_path(@routines)
  end

  private

  def routine_params
    params.require(:routine).permit(:name, :product_id, product_attributes: [
      :name,
      :active_ingredient_1,
      :active_ingredient_2
     ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/application/welcome.html.erb
<h1>Welcome to your Skin Shelf!</h1>
<% if user_signed_in? %>
    <h3>Check out your routines and products at the links above...</h3>
<% else %>
    <h3>Click on the links above to get started...</h3>
<% end %>
<h3><i>Fun Fact: The <%= @popular_product.keys[0] %> is the most popular product across all users!! </i></h3>

app/views/layouts/_nav.html.erb
<nav>
    <ul>
        <li><%= link_to 'Home', root_path %></li>
        <% if !user_signed_in? %>
            <li><%= link_to 'Signup', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% else %>
            <li><%= link_to 'Logout', destroy_user_session_path, method: "delete" %></li>
            <li>Hello, <%= current_user.username %></li>
            <li><%= link_to 'My Routines', routines_path %></li>
            <li><%= link_to 'My Products', products_path %></li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% if @products.empty? %>
    <h2>You don't have any products yet! </h2>
    <h4><br> Add a <%= link_to 'routine', routines_path %> first to show a list of your products!</h4>
<% else %>
    <h2>Here are all of the products you currently use:</h2>
    <% @products.each do |p| %>
    <%= link_to p.name, product_path(p) %> <br>
    <% end %>
    <h2>Strongest Products(with more than one active ingredient): </h2>
    <% @strong_products.each do |s| %>
        <%= s.name %> <br>
    <% end %>
    <br>
<% end %>

app/views/products/show.html.erb
<h2><%= link_to @product.name, product_routines_path(@product) %><h2>
<h3><%= @product.active_ingredient_1 %></h3>
<h3><%= @product.active_ingredient_2 %></h3>

app/views/routines/edit.html.erb
<h2>You are using <%= @routine.product.name %> in the <%= @routine.name %> routine </h2>

app/views/routines/index.html.erb
<% if @product %>
    <h2><%= @product.name %> is used in the following routines: </h2>
<% elsif @routines.empty? %>
    <h2>You don't have any routines yet!</h2>
<% else %>
    <h2>Here is a list of all your current routines:</h2>
<% end %>
<% @routines.each do |r| %>
    <%= link_to r.name, edit_routine_path(r) %> &emsp; <%= link_to "delete", routine_path(r), method: :delete, data: { confirm: "Are you sure?"} %> <br>
<% end %>

<p>
    <% if @product %>
        <%= link_to "Create a new routine for this product", new_product_routine_path(@product) %>
    <% else %>
        <%= link_to "Create New Routine", new_routine_path %>

    <% end %>
</p>

app/views/routines/new.html.erb
<% if @routine.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@routine.errors.count, "error") %> prohibited this routine from being saved:</h2>
  <ul>
    <% @routine.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<h1>Create a New Routine!</h1>
<p>
  <%= form_for @routine do |f| %> 
    <div>
        Name your routine: <%= f.text_field :name %><br>
    </div>
    <% if params[:product_id] %>
        <%= f.hidden_field :product_id, value: params[:product_id] %>
    
    <% else %>
        <p>Choose a product that you already have: </p>
        <div>
            <%= f.collection_select :product_id, current_user.products.uniq, :id, :name %>
        </div>
        
        <p>Or Add One! </p>
            <%= f.fields_for :product, @product do |p| %>
                <%= p.label :name %>
                <%= p.text_field :name %><br>
                <%= p.label :active_ingredient_1 %>
                <%= p.text_field :active_ingredient_1 %><br>
                <%= p.label :active_ingredient_2 %>
                <%= p.text_field :active_ingredient_2 %>
            <% end %>
    <% end %>
    <br>
    <%= f.submit %>
  <% end %>
</p>

app/views/routines/show.html.erb
<h1>You just added <%= @routine.name %> to your list of routines!</h1>